In [2]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

In [3]:
def Ai(i, M, X, Y, epsilon):
    """ indice i * tableau des masses * tableau des x * tableau des y * epsilon   ->  vecteur accélération
         int            array                array         array         float           couple (x,y) """
    G = 6.67*10**(-11)
    Fix = 0
    Fiy = 0
    
    for j in range(len(X)):
        #print('tour', j)
        #print(' ')
        Rij_x = X[j] - X[i]    #vecteur proj sur x
        Rij_y = Y[j] - Y[i]    #vecteur proj sur y
        rij2 = Rij_x**2 + Rij_y**2   #norme au carre
        #print('Rx ',Rij_x)
        #print('Ry ',Rij_y)
        #print('rij² ',rij2)
        #print(' ')
        
        Fix = Fix + (M[j]*Rij_x)/((rij2 + epsilon**2)**(3/2))
        Fiy = Fiy + (M[j]*Rij_y)/((rij2 + epsilon**2)**(3/2))
        #print('Fx ',Fix)
        #print('Fy ',Fiy)
        #print('  ')
        
        
    Aix = Fix*G
    Aiy = Fiy*G
    return Aix, Aiy

In [4]:
def instant_suivant(j,X0,Y0,Vx0,Vy0,M):
    X=X0
    #X = np.ones(len(X0))
    Y=Y0
    t=j*dt
    #M = 100000000000*np.ones(len(Y0))
    epsilon = 0.000001
    for i in range(len(X0)):
        Aix, Aiy = Ai(i, M, X, Y, epsilon)
        X[i] = ((Aix*(t**2/2)) + Vx0[i]*t +X0[i])
        Y[i] = ((Aiy*(t**2/2)) + Vy0[i]*t +Y0[i])
        #print(Vx0[i])
    return plt.plot(X,Y, 'bo')
    #return(X,Y)

In [28]:
dt = 0.01
N = 3
X0 = 0.1*np.random.randint(-10,11,N)
Y0 = 0.1*np.random.randint(-10,11,N)
Vx0 = 0.05*np.random.randint(-10,+11,N)
Vy0 = 0.05*np.random.randint(-10,+11,N)
M = 100000000000*np.ones(N)
#np.random.rand(10)
X0,Y0,Vx0,Vy0, Ai(0, M, X0, Y0, 0.0001),instant_suivant(1,X0,Y0,Vx0,Vy0,M),1+1,Vx0[0]+X0[0]

(array([ 0.90242674,  0.30681655,  0.69621877]),
 array([-0.39781899, -1.00142931, -0.80430969]),
 array([ 0.35,  0.5 , -0.3 ]),
 array([ 0.4 , -0.25, -0.5 ]),
 (-21.465130808352733, -36.379703099683397),
 2,
 1.2524267433968355)

In [29]:
fig = plt.figure()
plt.axis("equal")
ani = animation.FuncAnimation(fig, instant_suivant, frames=1000, interval=300,fargs=(X0,Y0,Vx0,Vy0,M), repeat=True)
plt.show()

# Bug de collision

In [7]:
'''M= np.array([10**23,10**25])
X0=np.array([0, 400000000])
Y0 = np.array([0, 0])
Vx0 = np.array([0,0])
Vy0 =np.array([0,1000]) '''

'M= np.array([10**23,10**25])\nX0=np.array([0, 400000000])\nY0 = np.array([0, 0])\nVx0 = np.array([0,0])\nVy0 =np.array([0,1000]) '

In [8]:
X0[0]= 0*5+ 2*1+2
X0

array([  4.        , -68.10717777,   0.80652817])