In [2]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Données : Vitesse circulaire (V) vitesse radiale (Vr) longitudes (L)
L = np.array([0,10,20,50,60,70,80,90,30,40,270,280,290,300,310,320,330,340,350])
Vr = np.array([132,154,158,54,31,6,10,5,106,64,121,96,84,79,65,63,28,6,4])

V0 = 220
R0 = 2.6265*10**17
V = np.empty(0)
R = np.empty(0)
for i in range(len(L)):
    V = np.append(V, Vr[i] + V0*np.sin(L[i]*3.1415/180))
    R = np.append(R, R0*np.sin(L[i]*3.1415/180))
#V, R
plt.plot(R, V, 'bo')
plt.show()
(R,V)

(array([  0.00000000e+00,   4.56073624e+16,   8.98290498e+16,
          2.01197228e+17,   2.27457516e+17,   2.46807030e+17,
          2.58657878e+17,   2.62650000e+17,   1.31321487e+17,
          1.68824023e+17,  -2.62649997e+17,  -2.58666327e+17,
         -2.46823674e+17,  -2.27481849e+17,  -2.01228510e+17,
         -1.68861305e+17,  -1.31363636e+17,  -8.98747841e+16,
         -4.56552932e+16]),
 array([ 132.        ,  192.20148386,  233.24230325,  222.52613786,
         221.52219144,  212.72966523,  226.65613232,  224.99999976,
         215.99705784,  205.40980413,  -98.99999788, -120.66320947,
        -122.7436064 , -111.54257305, -103.55234067,  -78.44103201,
         -82.03236203,  -69.2806111 ,  -34.24163147]))

In [2]:
#Données : L = 50° , R: distance centre_galaxie-nuage_de_gaz
Vr50 = np.array([-50,-16,6,23,54])
R50 = (10**20)*np.array([1.41,2.06,2.93,4.36,40.73])

# L = 90°
Vr90 = np.array([-76,-44,-28,5])
R90 = (10**20)*np.array([4.28,3.38,3.06,2.56])

# L = 135
Vr135 = np.array([-93,-83,-75,-49,-39,-15,-3])
R135 = (10**20)*np.array([-0.69,-0.80,-0.92, -1.73,-2.61,10.15,3.11])

# L = 20°
Vr20 = np.array([-24,-3,11,24,55,73,120])
R20 = (10**20)*np.array([2.98,2.67,2.49,2.35,2.06,1.93,1.64])


In [3]:
# Quadrant II : L = 135°

# Vr en fonction de R

L = 3.1415/180 *135
V0 = 220
R0 = 2.6265*10**17
R = R0
Vc = 200
while R < 3*R0:
    Vr = Vc*(R0/R)*np.sin(L)-V0*np.sin(L)
    plt.plot(R,Vr,'ro')
    R = R + 10**16

plt.show()

In [4]:
# Vr en fct de Vc

L = 3.1415/180 *135
V0 = 220
R0 = 2.6265*10**17
R = 2*R0
Vc = 200
while Vc < 2*V0:
    Vr = Vc*(R0/R)*np.sin(L)-V0*np.sin(L)
    plt.plot(Vc,Vr,'ro')
    Vc = Vc + 10

plt.show()

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation


# Données : Vitesse circulaire (V) vitesse radiale (Vr) longitudes (L)
L = np.array([0,10,20,50,60,70,80,90,30,40,270,280,290,300,310,320,330,340,350])
Vr = np.array([132,154,158,54,31,6,10,5,106,64,121,96,84,79,65,63,28,6,4])

V0 = 220
R0 = 2.6265*10**17
V = np.empty(0)
R = np.empty(0)
for i in range(len(L)):
    V = np.append(V, Vr[i] + V0*np.sin(L[i]*3.1415/180))
    R = np.append(R, R0*np.sin(L[i]*3.1415/180))
#V, R
plt.plot(R, V, 'go')





L = 3.1415/180 *135
V0 = 220
R0 = 2.6265*10**17
R = R0
Vc = 110
D = [-93,-83,-75,-49,-39,-15,-3]
color= 'ro'

for d in D:
    Vc = 110
    while Vc < 3*V0:
        while R < 2*R0:
            Vr = Vc*(R0/R)*np.sin(L)-V0*np.sin(L)
            if d -0.5<Vr and Vr<d +0.5:
                print(Vr, '   ', Vc,'   ' ,R)
                plt.plot(R, Vc, color)
                
            
            R = R + 10**16
        R = R0
        Vc = Vc + 10
    if color == 'ro':
        color = 'bo'
    else:
        color= 'ro'
    print(d)
plt.show()
0

-92.5600517633     140     4.1265e+17
-92.634789098     150     4.4265e+17
-92.7000389893     160     4.7265e+17
-92.7575001738     170     5.0265e+17
-93
-83.2912831877     110     2.8265e+17
-82.9890462797     130     3.3265e+17
-82.7657945822     150     3.8265e+17
-82.5941438779     170     4.3265e+17
-83.3118780566     180     4.6265e+17
-83.1137529207     200     5.1265e+17
-83
-74.9828551499     140     3.2265e+17
-75.1595168315     170     3.9265e+17
-74.555980375     180     4.1265e+17
-75.2827198826     200     4.6265e+17
-74.761610632     210     4.8265e+17
-75
-48.6425560195     180     3.1265e+17
-49.4881591984     190     3.3265e+17
-48.7884912967     220     3.8265e+17
-49.4798390973     230     4.0265e+17
-48.8892902902     260     4.5265e+17
-49.473983429     270     4.7265e+17
-48.9630886923     300     5.2265e+17
-49
-38.9724338632     190     3.0265e+17
-39.080690358     240     3.8265e+17
-38.5478375984     260     4.1265e+17
-39.1515080997     290     4.6265e+17
-

0

In [6]:
np.linspace(2.62*10**17,10**18,20)

array([  2.62000000e+17,   3.00842105e+17,   3.39684211e+17,
         3.78526316e+17,   4.17368421e+17,   4.56210526e+17,
         4.95052632e+17,   5.33894737e+17,   5.72736842e+17,
         6.11578947e+17,   6.50421053e+17,   6.89263158e+17,
         7.28105263e+17,   7.66947368e+17,   8.05789474e+17,
         8.44631579e+17,   8.83473684e+17,   9.22315789e+17,
         9.61157895e+17,   1.00000000e+18])

In [7]:
plt.plot(1,1,'ro')
plt.show()

In [8]:
10**17/10**21

0.0001

In [9]:
Vr

75.416659726063642

In [1]:
Vr = -10
if -100<Vr and Vr<0:
    Vr = 10
Vr

10

In [19]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation


# Données : Vitesse circulaire (V) vitesse radiale (Vr) longitudes (L)
L = np.array([0,10,20,50,60,70,80,90,30,40,270,280,290,300,310,320,330,340,350])
Vr = np.array([132,154,158,54,31,6,10,5,106,64,121,96,84,79,65,63,28,6,4])

V0 = 220
R0 = 2.6265*10**17
V = np.empty(0)
R = np.empty(0)
for i in range(len(L)):
    V = np.append(V, Vr[i] + V0*np.sin(L[i]*3.1415/180))
    R = np.append(R, R0*np.sin(L[i]*3.1415/180))
#V, R
plt.plot(R, V, 'go')





L = 3.1415/180 *135
V0 = 220
R0 = 2.6265*10**17
R = R0
Vc = 110
D = [-93,-83,-75,-49,-39,-15,-3]
color= 'ro'
SetV = set()
SetR = set()

for d in D:
    Vc = 110
    while Vc < 3*V0:
        while R < 2*R0:
            Vr = Vc*(R0/R)*np.sin(L)-V0*np.sin(L)
            if d -0.5<Vr and Vr<d +0.5:
                #print(Vr, '   ', Vc,'   ' ,R)
                SetV.add(Vc)
                SetR.add(R)
                plt.plot(R, Vc, color)
            
            R = R + 10**16
        R = R0
        Vc = Vc + 10
    
        
    if color == 'ro':
        color = 'bo'
    else:
        color= 'ro'
    #print(d)
#print(SetV,SetR)


#print(minV)
plt.show()


In [ ]:

        
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation


# Données : Vitesse circulaire (V) vitesse radiale (Vr) longitudes (L)
L = np.array([0,10,20,50,60,70,80,90,30,40,270,280,290,300,310,320,330,340,350])
Vr = np.array([132,154,158,54,31,6,10,5,106,64,121,96,84,79,65,63,28,6,4])

V0 = 220
R0 = 2.6265*10**17
V = np.empty(0)
R = np.empty(0)
for i in range(len(L)):
    V = np.append(V, Vr[i] + V0*np.sin(L[i]*3.1415/180))
    R = np.append(R, R0*np.sin(L[i]*3.1415/180))
#V, R
plt.plot(R, V, 'go')





L = 3.1415/180 *135
V0 = 220
R0 = 2.6265*10**17
R = R0
Vc = 110
D = [-93,-83,-75,-49,-39,-15,-3]
color= 'ro'
SetV = set()
SetR = set()

for d in D:
    Vc = 110
    while Vc < 3*V0:
        while R < 2*R0:
            Vr = Vc*(R0/R)*np.sin(L)-V0*np.sin(L)
            if d -0.5<Vr and Vr<d +0.5:
                #print(Vr, '   ', Vc,'   ' ,R)
                SetV.add(Vc)
                SetR.add(R)
                plt.plot(R, Vc, color)
            
            R = R + 10**16
        R = R0
        Vc = Vc + 10
    
    if len(SetV)!=0:
        minV = min(SetV)
        maxV = max(SetV)
        minR = min(SetR)
        maxR = max(SetR)

        Rmoy = maxR - minR
        Vmoy = maxV - minV

        plt.plot(Rmoy,Vmoy, 'yo')
        
    if color == 'ro':
        color = 'bo'
    else:
        color= 'ro'
    #print(d)
#print(SetV,SetR)


#print(minV)
plt.show()
